### ISSUE TITLE
Problem loading idapatcher.py in IDA v7.5.

### ISSUE THREAD

**Issue by Mulligan81** [iphelix/ida-patcher#2]
Hello.
I'd like to use the _ida-patcher_ in my IDA Pro v7.5 but after i've copied the _idapatcher.py_ file to the plugins folder i get _cannot import name 'Choose2' from 'idaapi'_... error. I've checked and there is a class _Choose2_ defined in the _ida_kernwin.py_ file imported by _idaapi.py_ by the _idapatcher.py_ so I completely don't understand why does the error occur.

**Comment by ghost** [comment]
Hi, I made fork version for IDA 7.5 and Python 3.

https://github.com/y0ny0ns0n/ida-patcher

I checked it is working on IDA 7.5.201028
